version: '3'
services:
  nginx:
    image: 'johnsnow-cn-north-1.jcr.service.jdcloud.com/nginx:latest'
    ports: 
      - "80:80"
    links:
      - web
    depends_on:
      - web
    volumes:
      - ./volumes/config/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/log/nginx:/var/log/nginx
  web:
    image: 'johnsnow-cn-north-1.jcr.service.jdcloud.com/frontend:v0.0.2'
    ports:
      - "5000:5000"
    environment:
      - ACCOUNT_TOKEN: <token>
      - BASE_URI: <base_uri>